version: "3.3"
services:

  #1 Worker
  worker:
    image: "sudoanand/piesocket-worker:${PIE_HTTPD_VERSION}" 
    container_name: worker
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      # - PIE_SKIP_CONNECTION_DECREASE=1
      # - PIE_SKIP_PRESENCE_SYNC=1
      - PIE_SOCKET_HOST=piehttpd
      - PIE_REDIS_CHANNEL=messages

      - PIE_MYSQL_HOST=${PIE_MYSQL_HOST}
      - PIE_MYSQL_USER=${PIE_MYSQL_USER}
      - PIE_MYSQL_PASSWORD=${PIE_MYSQL_PASSWORD}
      - PIE_MYSQL_DATABASE=${PIE_MYSQL_DATABASE}

      - PIE_REDIS_URL=${PIE_REDIS_CACHE}
      - PIE_REDIS_ANALYTICS_URL=${PIE_REDIS_ANALYTICS}

      - PIE_LOG_LEVEL=${PIE_LOG_LEVEL}
    volumes:
      - ./mnt:/mnt
    extra_hosts:
        - "piehttpd:127.0.0.1"
    ulimits:
      nofile:
        soft: "200000"
        hard: "1000000"

  #2 Pusher-worker
  pusher:
    image: "sudoanand/piesocket-worker-v4:${PIE_PUSHER_VERSION}" 
    container_name: pusher
    ports:
      - "6001:6001"
    environment:
      - SOKETI_ADAPTER_DRIVER=redis
      - SOKETI_ADAPTER_REDIS_PREFIX=v4
      
      - SOKETI_DB_REDIS_HOST=${PIE_REDIS_PUSHER_HOST}
      - SOKETI_DB_REDIS_PORT=${PIE_REDIS_PUSHER_PORT}
      - SOKETI_DB_REDIS_DB=${PIE_REDIS_PUSHER_DB}
      - SOKETI_DB_REDIS_USERNAME=${PIE_REDIS_PUSHER_USERNAME}
      - SOKETI_DB_REDIS_PASSWORD=${PIE_REDIS_PUSHER_PASSWORD}
      - SOKETI_DB_REDIS_KEY_PREFIX=${PIE_REDIS_PUSHER_KEY_PREFIX}

      - SOKETI_APP_MANAGER_DRIVER=mysql
      - SOKETI_DB_MYSQL_HOST${PIE_MYSQL_HOST}
      - SOKETI_DB_MYSQL_PORT=${PIE_MYSQL_PORT}
      - SOKETI_DB_MYSQL_USERNAME=${PIE_MYSQL_USER}
      - SOKETI_DB_MYSQL_PASSWORD=${PIE_MYSQL_PASSWORD}
      - SOKETI_DB_MYSQL_DATABASE=${PIE_MYSQL_DATABASE}
      

  #3 Publisher
  publisher:
    image: "sudoanand/piesocket-publisher:${PIE_PUBLISHER_VERSION}" #stable-history: v5.0.1 v5.0.0, v4.3.1
    container_name: publisher
    ports:
      - "8082:8082"
    environment:
      - PIE_REDIS_URL=${PIE_REDIS_CACHE}

      - PIE_MYSQL_HOST=${PIE_MYSQL_HOST}
      - PIE_MYSQL_USER=${PIE_MYSQL_USER}
      - PIE_MYSQL_PASSWORD=${PIE_MYSQL_PASSWORD}
      - PIE_MYSQL_DATABASE=${PIE_MYSQL_DATABASE}
      - PIE_MYSQL_PORT=${PIE_MYSQL_PORT}

      - PIE_MONGO_URL=${PIE_MONGO_URL_LOGS}
    ulimits:
      nofile:
        soft: "200000"
        hard: "1000000"

  #4 Connection and message count processor 
  analytics:
    image: "sudoanand/piesocket-worker-analytics:${PIE_ANALYTICS_VERSION}"
    container_name: analytics
    volumes:
      - ./mnt:/mnt
    ports:
      - "8083:8083"
    environment:
      - PIE_REDIS_URL=${PIE_REDIS_CACHE}
      - PIE_REDIS_ANALYTICS_URL=${PIE_REDIS_ANALYTICS}

      - PIE_MONGO_URL=${PIE_MONGO_URL_LOGS}

      - PIE_LOG_DIR=/mnt/storage/logs
